# Generated by Django 3.2.9 on 2021-11-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres del autor')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos del autor')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='Nacionalidad del autor')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook del autor')),
                ('Instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram del autor')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter del autor')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web del autor')),
                ('email', models.EmailField(max_length=254, verbose_name='Email del autor')),
                ('estado', models.BooleanField(default=True, verbose_name='Autor activo/no Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cracion')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'Autor',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoria')),
                ('estado', models.BooleanField(default=True, verbose_name='Categoria Activada/Desactivada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
    ]
